Deployment
Mutai-Gilbert/budget_manager pull request #2
Opened 2023-07-18 18:11 UTC by Mutai-Gilbert

Finally Deployment

2023-07-19 16:13 UTC, Nemwel-Boniface requested changes
##  Hello @Mutai-Gilbert  :wave: 
### This is a manual review
#   :recycle:  Request Changes :recycle: 

- [ ] Good job working on your project so far! However, there are some issues remaining to move to the next step.


![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

**I have to add the changes here as I am not able to highlight them in the "files changed"**

- [x] You did well in the video presentation. However, you seem to not have mentioned the aim/ purpose of the application you built. What is is mainly supposed to be used for? What will it help me achieve? Kindly retake the video demo and in the new video kindly include the aim for building the project.

- [x] Your project seems to not have any mechanism of "data Encapsulation" when you create two accounts and create your records and then login, you will see them even in the new account despite you not creating the records in this new account. This is caused because in your categories index action, you are basically fetching all the records instead of fetching the records that only belong to a specific user. Kindly update the index action to only show data the currently logged-in user alone. 

- [x] In your home page "Categories, I seem to not be able to logout from your application. The only way I found to be able to logout is that I have to click on "Add category" then I will be able to see the logout button. Kindly ensure that this button is included in all the relevant pages of your application including the Categories page.

**This is how I am seeing it right now:**

[Screencast from 19-07-2023 06:58:33 ALASIRI.webm](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/0a4955fe-3a65-4179-b964-ef0ce07a64d7)

- [x] It is always a beautiful scene when we see tests in projects :clap: . However, I got the below error when I was running ```rspec spec``` and all the tests basically failed.

![Screenshot from 2023-07-19 19-04-08](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/3e59545d-213e-4c36-ae78-07add342ab1c)

However, when I used ``` bundle exec rspec spec``` the tests then run but with a few failing tests which I will include a screenshot below:

![image](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/08e578af-7595-4ab2-9ab8-c1b51e73ae58)

![image](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/5f0757df-ed75-4e8f-9b93-0ff2a3a15caf)

**In relation to the comment above about the failing linters, kindly do the following:**
- [x] KIndly update your README to include ```bundle exec rspec spec``` as the alternative command to run the tests
- [x] Kindly ensure that all the failing tests are passing correctly 


Cheers, and Happy coding!

2023-07-19 16:13 UTC, Nemwel-Boniface commented on README.md
While I am not able to highlight all the sections of the README, I will describe the section I mean.

- [x] When I started your project locally I got an error. The error was however solved by running ```rake assets:precompile``` to pre-compile the assets before they were used. KIndly ensure that you include this in your documentation to ease the process of setting up the project locally and using it.

**This is the error I got:**

![Screenshot from 2023-07-19 18-04-10](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/96d281d2-517c-414f-a31a-5cad4df958d0)

2023-07-20 20:33 UTC, Mutai-Gilbert commented on README.md
Done

2023-07-20 20:35 UTC, Mutai-Gilbert commented on README.md
Done

2023-07-21 14:10 UTC, Nemwel-Boniface approved these changes
##  Hello @Mutai-Gilbert  :wave: 
### This is a manual review
#   :heavy_check_mark: Approve :heavy_check_mark: 

- [x] Thank you for making the changes I had requested :rocket: 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

All the tests pass here :partying_face: 

![image](https://github.com/Mutai-Gilbert/budget_manager/assets/86318284/6e71fe85-6029-472b-8db3-22869ab9cb71)


Cheers, and Happy coding!

2023-07-21 15:34 UTC, bellom commented
@Mutai-Gilbert - kindly go ahead and merge!

2023-07-21 15:46 UTC, merged